### PR TITLE
typo: "an sheared" --> "a sheared"

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by cquammen** [comment]
Mind posting this patch to Kitware's GitLab?

https://gitlab.kitware.com/vtk/vtk

**Comment by waldyrious** [comment]
@cquammen I'm on it :) I'll close the PR as soon as I get it sorted out in the gitlab side.

**Comment by waldyrious** [comment]
Ok, copied the commit to my gitlab fork and submitted a merge request there: https://gitlab.kitware.com/vtk/vtk/merge_requests/887

**Comment by waldyrious** [comment]
For reference, here are the steps I took to move my PR to gitlab (reusing the same commits, rather than redoing it all from scratch):

First I signed up at [Kitware's gitlab](https://gitlab.kitware.com/users/sign_in) (using my github account, for convenience)

Then I forked the [vtk project](https://gitlab.kitware.com/vtk/vtk) using gitlab's web interface (just like here on github).

Then I ran the following commands:

Create a local clone of my gitlab fork:
**$ git clone git@gitlab.kitware.com:waldyrious/vtk.git**
> Cloning into 'vtk'...
> (...)
> Checking out files: 100% (15656/15656), done.

Enter the local repository:
**$ cd vtk**

Add a remote reference to the canonical vtk repository at gitlab:
**$ git remote add upstream git@gitlab.kitware.com:vtk/vtk.git**

Ensure I got the latest master branch from gitlab:
**$ git pull upstream master**

Add a remote reference to my github fork, so I can fetch the PR branch
**$ git remote add github https://github.com/waldyrious/VTK.git**

Fetch the PR branch from github:
**$ git fetch github patch-1**
> `From https://github.com/waldyrious/VTK`
> ` * branch            patch-1    -> FETCH_HEAD`
> ` * [new branch]      patch-1    -> github/patch-1`

Switch over to the PR branch:
**$ git checkout patch-1**
> `Checking out files: 100% (229/229), done.`
> `Branch patch-1 set up to track remote branch patch-1 from github.`
> `Switched to a new branch 'patch-1'`

Rebase my patch on gitlab's latest master, to ensure there are no merge conflicts:
**$ git rebase master**
> `First, rewinding head to replay your work on top of it...`
> `Applying: typo: "an sheared" --> "a sheared"`

Rename the branch. Not required, but a nice touch.
**$ git branch -m doc-typo**

Push the branch to my gitlab fork:
**$ git push -u origin doc-typo**
> `(...)`
> `To git@gitlab.kitware.com:waldyrious/vtk.git`
> ` * [new branch]      doc-typo -> doc-typo`
> `Branch doc-typo set up to track remote branch doc-typo from origin.`

Then I just went to https://gitlab.kitware.com/waldyrious/vtk and voilá, there was a notification of a new "doc-typo" branch with fresh commits.

I clicked the button to create a merge request and the rest is the same as in github :)

**Pull request closed without merging**
