### PR TITLE
Fix vector plots

### PR DESCRIPTION
**Pull request by aashish24**
@sankhesh please review.

### CODE REVIEW

**Comment by cquammen** [comment]
@aashish24 Is there a particualr reason you are using GitHub's pull request mechanism rather than GitLab?

**Comment by waldyrious** [comment]
@aashish24 If it helps, here's [the step-by-step process](https://github.com/Kitware/VTK/pull/23#issuecomment-154597383) by which I moved my PR from github to gitlab. That way you should be able to preserve the commits you've already made, instead of redoing the patch from scratch (although the fact that there are merge conflicts may be an obstacle).

**Comment by aashish24** [comment]
@cquammen  @waldyrious Sorry, this PR was not supposed to be here. We have our own fork at UVCDAT/VTK sot that we can push some quick changes to that and then we create PR's in VTK/gitlab. 

@waldyrious thanks! I work for Kitware and have been working on Virtual Reality, Volume Rendering, and Geospatial and Geophysical code.

**Comment by waldyrious** [comment]
@aashish24 ha, I suspected you already were familiar with the dev process, but since for another recent PR of yours (#24) you closed it without saying why, I wasn't entirely sure (I've seen people close PRs in inactive projects out of frutstration due to nonresponsiveness of the maintainers), so I figured it wouldn't hurt to add my 2 cents, just in case :)

**Comment by aashish24** [comment]
@waldyrious thanks, I appreciate it. I didn't realize that we have some activity here at github as well. I closed the PR as soon as I realized my mistake. By default, kitware/vtk comes as the first option.

**Pull request closed without merging**
