### PR TITLE
Xdmf3 fixes

### PR DESCRIPTION
**Pull request by nschloe**
This PR fixes the build of Xdmf3 for system libxml2/HDF5. Additonally, it clarifies the logic for libxml2 finding.

### CODE REVIEW

**Comment by anatol** [comment]
Thanks. I found these changes useful. Any chance to see it merged?

**Comment by cquammen** [comment]
Mind posting this patch to Kitware's GitLab?

https://gitlab.kitware.com/vtk/vtk

**Comment by waldyrious** [comment]
@nschloe If it helps, here's [the step-by-step process](https://github.com/Kitware/VTK/pull/23#issuecomment-154597383) by which I moved my PR from github to gitlab. That way you should be able to preserve the commits you've already made, instead of redoing the patch from scratch.

**Comment by nschloe** [comment]
Thanks for the positive feedback.

Unfortunately, I won't find time to go through the 15-step process of signing up on the GitLab instance and searching my way through the webinterface, just to get this PR into master. The code is here, and if you find it useful, feel free to merge it, whatever process may be necessary for that to happen. If you absolutely cannot accept PRs on GitHub, I would suggest removing the GitHub since it encourages people to fork and PR, eventually in vain.

Anyhow, thanks for all your great work on VTK!

**Comment by waldyrious** [comment]
@nschloe I think I might be able to migrate the PR myself; it should retain authorship information, but I'd just ask you to [sign up on gitlab](https://gitlab.kitware.com/users/sign_in) (should be ~30 seconds if you use the github authentication method) so that it gets properly attributed to you.

I've already [submitted a proposed change](https://gitlab.kitware.com/vtk/vtk/merge_requests/888) to make the instructions clearer to github folk. I'm currently waiting for it to get merged (ping @cquammen).

Note: I'm just a volunteer contributor ([first commit made just a few days ago](https://github.com/Kitware/VTK/commits?author=waldyrious)), in case that wasn't clear :)

**Comment by nschloe** [comment]
Thanks @waldyrious!

I signed up at GitLab, but I wouldn't mind if it doesn't get properly attributed either.

**Comment by waldyrious** [comment]
Here it is :) https://gitlab.kitware.com/vtk/vtk/merge_requests/918
@nschloe please check if it looks good and close this PR.

**Comment by nschloe** [comment]
Thanks! Once [the PR on GitLab](https://gitlab.kitware.com/vtk/vtk/merge_requests/918) is merged, I'll close this one.

**Comment by waldyrious** [comment]
:+1:

**Comment by waldyrious** [comment]
@nschloe I'm not sure if you're getting notifications of updates in the gitlab merge request, but there has been some comments you might want to take a look at, specifically from @demarle.

**Comment by nschloe** [comment]
I'm reading the updates, thank you.

**Comment by waldyrious** [comment]
@nschloe the merge request at kitware was closed, but as I'm not familiar with this module, I am not sure I understood the resolution. Is this fix no longer necessary, already applied otherwise, or does it still need to be done elsewhere?

**Comment by nschloe** [comment]
Closed and not merged? Great.

I have no idea if it should still be necessary. I hear lots of things changed with Xdmf3 in the past year.

**Comment by bradking** [comment]
@nschloe @waldyrious I think @demarle superseded [MR 918](https://gitlab.kitware.com/vtk/vtk/merge_requests/918) with [MR 1571](https://gitlab.kitware.com/vtk/vtk/merge_requests/1571).

**Pull request closed without merging**
