### PR TITLE
'≤' character causes bug in non-european language

### PR DESCRIPTION
**Pull request by rcfwgithub**
'≤'  stops the python binding from init vtk in non-european language env
change to <= will fix this

### CODE REVIEW

**Comment by mathstuf** [comment]
Thanks. Please see `CONTRIBUTING.md` and submit a merge request to [our GitLab instance](https://gitlab.kitware.com/vtk/vtk/) instead. You can use GitHub OAuth to sign in if preferred.

**Comment by luzpaz** [comment]
@rcfwgithub opened a MR for you on gitlab: https://gitlab.kitware.com/vtk/vtk/merge_requests/4052

**Comment by mathstuf** [comment]
Closing; the MR has been merged.

**Comment by mathstuf** [comment]
Oh, I don't have close permissions :/ . @bradking?

**Pull request closed without merging**
