### PR TITLE
vtkInteractorStyleFlight fix

### PR DESCRIPTION
**Pull request by Robertson-Brian**
Work stopped on an un-working flight interactor style in 2002. These minimal changes implement basic "flight" functionality.

### CODE REVIEW

**Comment by mathstuf** [comment]
Thanks. Please see `CONTRIBUTING.md` and submit a merge request to [our GitLab instance](https://gitlab.kitware.com/vtk/vtk/) instead. You can use GitHub OAuth to sign in if preferred.

**Comment by luzpaz** [comment]
@Robertson-Brian is this patch still relevant ? Was it submitted to gitlab ?

**Comment by Robertson-Brian** [comment]
I attempted to submit to gitlab, but received no confirmation. I see no reason why it would not still work, but I am no longer regularly working with VTK so I haven't used it in a while. (if anyone knows the correct way, and wants to, feel free to submit the changes to gitlab. Just let me know if the code is accepted, so I can put it on my resume)

**Comment by mathstuf** [comment]
What do you mean by "no confirmation"?

**Comment by Robertson-Brian** [comment]
I followed the Contribution guide, but received no confirmation or indication that it worked or failed.

**Comment by Robertson-Brian** [comment]
That was about a year ago.

**Comment by mathstuf** [comment]
I'm not seeing a merge request on VTK for this (or a fork of VTK by just searching for your username), so something seems to have went wrong before step 2 from what I'm seeing. What did you try that didn't work?

**Comment by Robertson-Brian** [comment]
I didn't run into any problems, but I also didn't get any confirmation anything worked, I guess that's what I mean. I'm not really at a place I can work on this now. Maybe in a few months.

**Comment by mathstuf** [comment]
It'd be great if you could show what you tried so that we can try and figure out what might have went wrong.

**Pull request closed without merging**
