### PR TITLE
Two files need to be modified.

### PR DESCRIPTION
**Pull request by jiapei100**
1) IO/FFMPEG/vtkFFMPEGWriter.cxx
**ffmpeg 3.x compatibility**

2) Rendering/GL2PSOpenGL2/vtkOpenGLGL2PSHelperImpl.cxx
**gl2psAddPolyPrimitive** function parameters 

Cheers
Pei

### CODE REVIEW

**Comment by mathstuf** [comment]
Thanks. Please see `CONTRIBUTING.md` and submit a merge request to [our GitLab instance](https://gitlab.kitware.com/vtk/vtk/) instead. You can use GitHub OAuth to sign in if preferred.

**Comment by luzpaz** [comment]
@jiapei100 is this still relevant ? If so I can submit the patch for you on gitlab

**Comment by mathstuf** [comment]
I believe that @utkarshayachit has added support for FFmpeg 3, but I'm not sure.

**Comment by jhlegarreta** [comment]
Saw these PRs just by chance.

The changes (fc6b3bd) to `vtkFFMPEGWriter.cxx` were addressed in ffb53e9b; however the ones to `vtkOpenGLGL2PSHelperImpl.cxx` (4a104a6) have not made their way into VTK master.

@bradking @utkarshayachit  any suggestions?

Also, note that VTK uses GitLab to host the code and that this is just a mirror of that:
https://gitlab.kitware.com/vtk/vtk

Contributing is as easy:
https://gitlab.kitware.com/vtk/vtk/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
