### PR TITLE
Misc. doxy and comment typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
@marcelotrevisani should I rebase ?

**Comment by marcelotrevisani** [comment]
@luzpaz sure, thanks  :)

**Comment by marcelotrevisani** [comment]
@luzpaz Actually you have to do that in gitlab
[Gitlab VTK repository](https://gitlab.kitware.com/vtk/vtk/merge_requests)

**Comment by luzpaz** [comment]
@marcelotrevisani sorry, don't know how to do it on gitlab. Do you mind submitting it there?

**Comment by mathstuf** [comment]
Please see https://gitlab.kitware.com/vtk/vtk/merge_requests/3424. This can then be closed.

**Comment by luzpaz** [comment]
Thanks @mathstuf
Closing PR

**Pull request closed without merging**
